apiVersion: v1                 
kind: Service                  
metadata:                      
  labels:                      
    app: nginx-svc                 
  name: nginx-svc                  
spec:                          
  ports:                       
  - name: http            
    port: 8081                 
    protocol: TCP              
    targetPort: 80           
  selector:                    
    app: bgd                
  type: ClusterIP                       
