apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: toto
  name: keycloak-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toto
  template:
    metadata:
      labels:
        app: toto
    spec:
      containers:
        - image: nginx
          name: toto
          env:
            - name: COLOR
              value: "blue"
